name: KOTH
main: dev.fadest.koth.KOTHPlugin
description: A King of the Hill game mode with many features
version: 1.0-SNAPSHOT
author: Fadest
commands:
  koth:
    description: Main command of the KOTH plugin
    aliases: [ king, hill, hills, game, games, koths, arena ]